### ISSUE TITLE
Incorrect output when `y` flag used

### ISSUE THREAD

**Issue by simevidas** [chipto/regexly#2]
With this input:

```
regexp = /foo/y
string = foofoo
```

the `regexp.exec(string)` value is `null`, but the value should be the same as when the `g` flag is used (at least in this case, IIUC; try in the browser’s console).

![foo](https://user-images.githubusercontent.com/716405/30758275-f4a84bee-9fd1-11e7-90d5-a96c4091c4f5.png)

**Comment by zikaari** [comment]
Thanks for the heads up. The issue is being caused by use of same `RegExp` object (reference) for all the operations.
Given the same variables, if `string.match(regexp)` is called before `exec`, the value is `null`.

So the fix would be to "clone" the regex object instead of sharing between those calls. 
Right now I'm in the process of migrating Regexly to dockerized setup on AWS (v0.2.0 will have server backed permalinks) so this fix will also land in v0.2.0. It's taking longer than usual because of my lack of experience with docker and aws.
